default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: itassetmanager
  username: postgres
  password: sqlpass
  host: 103.228.83.115

production:
  <<: *default
  url: <%= ENV['CUSTOM_DATABASE_URL'] %>
