default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: itassetmanager
  username: postgres
  password: Cylsys@027
  host: localhost

production:
  <<: *default
  url: <%= ENV['CUSTOM_DATABASE_URL'] %>
