default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
 

development:
  <<: *default
  database: itassetmanager
  username: postgres
  password: Pk@7470588990
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['CUSTOM_DATABASE_URL'] %>
